import type { Control, Preset } from "@/components/customize/types"

/** Optical settings every glass surface understands (see `LiquidGlass`). */
export const glassControls: Control[] = [
  {
    kind: "number",
    key: "ior",
    label: "Refractive index",
    description: "Index of refraction: 1 is air, 1.33 water, 1.5 glass, 2.42 diamond.",
    default: 1.5,
    min: 1,
    max: 3,
    step: 0.01,
  },
  {
    kind: "select",
    key: "surface",
    label: "Surface",
    description: "Cross-section of the rim.",
    type: '"squircle" | "circle" | "concave" | "lip"',
    default: "squircle",
    options: ["squircle", "circle", "concave", "lip"],
  },
  {
    kind: "number",
    key: "thickness",
    label: "Thickness",
    description: "Height of the glass as a multiple of the bezel width.",
    default: 2.4,
    min: 0,
    max: 6,
    step: 0.1,
    unit: "×",
  },
  {
    kind: "number",
    key: "bezel",
    label: "Bezel",
    description: "Width of the refracting rim in px. Defaults to ~40% of the shortest side.",
    default: null,
    min: 2,
    max: 60,
    step: 1,
    unit: "px",
    auto: "Auto",
  },
  {
    kind: "number",
    key: "dispersion",
    label: "Dispersion",
    description: "Chromatic split at the rim (0 – 1).",
    default: 0.12,
    min: 0,
    max: 1,
    step: 0.01,
  },
  {
    kind: "number",
    key: "specular",
    label: "Specular",
    description: "Strength of the light catching the rim (0 – 1).",
    default: 0.2,
    min: 0,
    max: 1,
    step: 0.01,
  },
  {
    kind: "number",
    key: "lightAngle",
    label: "Light angle",
    description: "Direction the light comes from, in degrees (0 = right, -90 = top).",
    default: -60,
    min: -180,
    max: 180,
    step: 1,
    unit: "°",
  },
  {
    kind: "number",
    key: "blur",
    label: "Blur",
    description: "Backdrop blur in px. Liquid glass bends light — keep it small.",
    default: null,
    min: 0,
    max: 12,
    step: 0.5,
    unit: "px",
    auto: "Auto",
  },
  {
    kind: "number",
    key: "saturation",
    label: "Saturation",
    description: "Backdrop saturation multiplier.",
    default: 1.6,
    min: 0,
    max: 3,
    step: 0.05,
  },
  {
    kind: "select",
    key: "variant",
    label: "Material",
    description: "`clear` is fully transparent; `frosted` adds a tint for legible text.",
    type: '"clear" | "frosted"',
    default: "clear",
    options: ["clear", "frosted"],
  },
  {
    kind: "color",
    key: "tint",
    label: "Tint",
    description: "Colour laid over the glass. Defaults to `--glass-tint`.",
    type: "string",
    default: null,
    auto: "Theme",
  },
  {
    kind: "boolean",
    key: "shadow",
    label: "Shadow",
    description: "Draw the soft outer shadow.",
    default: true,
  },
]

export const glassKeys = glassControls.map((c) => c.key)

export const glassPresets: Preset[] = [
  { name: "Liquid Glass", values: {} },
  {
    name: "Water",
    values: { ior: 1.33, surface: "circle", thickness: 1.8, dispersion: 0.04, specular: 0.15 },
  },
  {
    name: "Crystal",
    values: { ior: 1.9, thickness: 3, dispersion: 0.3, specular: 0.5 },
  },
  {
    name: "Diamond",
    values: { ior: 2.42, thickness: 3.4, dispersion: 0.45, specular: 0.8, saturation: 1.9 },
  },
  { name: "Bubble", values: { surface: "lip", ior: 1.6, thickness: 3, specular: 0.6 } },
  { name: "Dish", values: { surface: "concave", thickness: 2, dispersion: 0.2 } },
  { name: "Frosted", values: { variant: "frosted", blur: 4, specular: 0.1 } },
  { name: "Subtle", values: { ior: 1.2, thickness: 1.4, dispersion: 0, specular: 0.1 } },
]
