// Generates, from registry/index.ts:
//   registry.json                 consumed by `shadcn build` and GitHub-address installs
//   app/opaline.css               the site's copy of the theme tokens
//   public/llms.txt               index for LLMs and agents (llmstxt.org)
//   public/llms-full.txt          every component's install + usage in one file
//   public/components/<name>.md   per-component markdown (also "Copy page")
//
//   REGISTRY_URL  public URL where built items are served (no trailing slash)

import { mkdirSync, writeFileSync } from "node:fs"

import {
  categoryLabels,
  docItems,
  items,
  keyframes,
  type Item,
} from "../registry/index.ts"
import { componentMarkdown } from "../registry/markdown.ts"
import {
  dark,
  fontMono,
  fontSans,
  glassKeys,
  light,
  pick,
} from "../registry/theme.ts"

const REGISTRY_URL = (
  process.env.REGISTRY_URL ?? "https://opaline.buildlab.in/r"
).replace(/\/$/, "")
const HOMEPAGE = REGISTRY_URL.replace(/\/r$/, "")

const url = (name: string) => `${REGISTRY_URL}/${name}.json`

function toRegistryItem(item: Item) {
  const out: Record<string, unknown> = {
    name: item.name,
    type: item.type,
    title: item.title,
    description: item.description,
  }
  if (item.dependencies?.length) out.dependencies = item.dependencies
  const registryDependencies = (item.internal ?? []).map(url)
  if (registryDependencies.length) out.registryDependencies = registryDependencies
  if (item.files.length) out.files = item.files

  if (item.name === "theme") {
    out.cssVars = {
      theme: { "font-sans": fontSans, "font-mono": fontMono },
      light,
      dark,
    }
    out.css = {
      "@layer base": {
        body: {
          "-webkit-font-smoothing": "antialiased",
          "-moz-osx-font-smoothing": "grayscale",
          "letter-spacing": "-0.011em",
          "text-rendering": "optimizeLegibility",
        },
      },
    }
  } else if (item.glass) {
    out.cssVars = { light: pick(light, glassKeys), dark: pick(dark, glassKeys) }
  }

  if (item.keyframes?.length) {
    out.css = Object.fromEntries(
      item.keyframes.map((k) => [`@keyframes ${k}`, keyframes[k]])
    )
  }
  return out
}

const registry = {
  $schema: "https://ui.shadcn.com/schema/registry.json",
  name: "opaline",
  homepage: HOMEPAGE,
  items: [
    ...items.map(toRegistryItem),
    {
      name: "all",
      type: "registry:item",
      title: "Everything",
      description: "The Opaline theme and every component in one install.",
      registryDependencies: items
        .filter((i) => i.category !== "foundation" || i.name === "theme")
        .map((i) => url(i.name)),
    },
  ],
}

writeFileSync("registry.json", JSON.stringify(registry, null, 2) + "\n")

// Site theme stylesheet, generated from the same tokens.
const block = (sel: string, vars: Record<string, string>) =>
  `${sel} {\n${Object.entries(vars)
    .map(([k, v]) => `  --${k}: ${v};`)
    .join("\n")}\n}\n`
const frames = Object.entries(keyframes)
  .map(
    ([name, steps]) =>
      `@keyframes ${name} {\n${Object.entries(steps)
        .map(
          ([step, decl]) =>
            `  ${step} { ${Object.entries(decl)
              .map(([p, v]) => `${p}: ${v};`)
              .join(" ")} }`
        )
        .join("\n")}\n}\n`
  )
  .join("\n")

writeFileSync(
  "app/opaline.css",
  `/* Generated by scripts/generate-registry.mts — do not edit. */\n\n` +
    block("@theme", { "font-sans": fontSans, "font-mono": fontMono }) +
    "\n" +
    block(":root", light) +
    "\n" +
    block(".dark", dark) +
    "\n" +
    frames
)

// --- LLM-friendly docs --------------------------------------------------

const md = (item: Item) =>
  componentMarkdown(item, { homepage: HOMEPAGE, registryUrl: REGISTRY_URL })

const setup = `## Setup

Opaline is a shadcn registry. It needs React 19, Tailwind CSS v4 and a
components.json (run \`npx shadcn@latest init\` first).

Register the namespace once in components.json:

\`\`\`json
{ "registries": { "@opaline": "${REGISTRY_URL}/{name}.json" } }
\`\`\`

Then install the theme and any component:

\`\`\`bash
npx shadcn@latest add @opaline/theme @opaline/glass-button
npx shadcn@latest add @opaline/all   # everything
\`\`\`

Components install to components/ui and import from "@/components/ui/<name>".
Glass components refract the backdrop in Chromium browsers and fall back to
frosted blur in Safari and Firefox. Place them over colourful content.
`

const sections = (Object.keys(categoryLabels) as (keyof typeof categoryLabels)[])
  .map((cat) => {
    const list = docItems.filter((i) => i.category === cat)
    if (!list.length) return ""
    return [
      `## ${categoryLabels[cat]}`,
      "",
      ...list.map(
        (i) => `- [${i.title}](${HOMEPAGE}/components/${i.name}.md): ${i.description}`
      ),
      "",
    ].join("\n")
  })
  .join("\n")

const llms = `# Opaline

> Liquid glass and premium, minimal React components — Tailwind CSS v4 + Radix,
> distributed as a shadcn registry. Install any item with
> \`npx shadcn@latest add @opaline/<name>\`.

${setup}
${sections}
## Optional

- [Registry index](${REGISTRY_URL}/registry.json): machine-readable list of every item
- [Full docs](${HOMEPAGE}/llms-full.txt): install and usage for every component in one file
- [Source](https://github.com/deepraj21/opaline)
`

writeFileSync("public/llms.txt", llms)
writeFileSync(
  "public/llms-full.txt",
  `# Opaline — full reference\n\n${setup}\n` +
    docItems.map((i) => md(i).replace(/^# /, "## ").replace(/\n## /g, "\n### ")).join("\n---\n\n")
)
mkdirSync("public/components", { recursive: true })
for (const item of docItems) {
  writeFileSync(`public/components/${item.name}.md`, md(item))
}

console.log(`registry.json: ${registry.items.length} items → ${REGISTRY_URL}`)
